 # Generated by Django 2.2.6 on 2019-12-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_remove_element_type_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='element_classification',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
