# Generated by Django 2.2.6 on 2019-12-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_element_classification_element_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element_classification',
            name='create_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='element_classification',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
