# Generated by Django 2.2.6 on 2019-12-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_auto_20191219_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element_classification',
            name='create_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
