# Generated by Django 2.2.6 on 2020-01-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_auto_20191227_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element_classification',
            name='element_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.Element_Type'),
        ),
    ]
