# Generated by Django 2.2.6 on 2020-01-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=50)),
                ('status', models.BooleanField(null=True)),
                ('create_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
