# Generated by Django 2.2.6 on 2020-01-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protection_Barrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='work_activities',
            field=models.ManyToManyField(blank=True, to='equipment.Work_Activities'),
        ),
    ]
