# Generated by Django 2.2.6 on 2020-01-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20200109_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
