# Generated by Django 2.2.6 on 2020-01-07 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('body_configuration', '0001_initial'),
        ('size_configuration', '0002_auto_20200107_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='body_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='body_configuration.BodyPart'),
        ),
        migrations.AddField(
            model_name='size',
            name='description',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='gender',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='Body_Size',
        ),
    ]
