# Generated by Django 2.2 on 2020-01-27 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_auto_20200102_0911'),
        ('requestType', '0002_auto_20200124_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_type',
            old_name='Status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='request_type',
            name='element_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurations.Element_Type'),
        ),
        migrations.AlterField(
            model_name='request_type',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
