# Generated by Django 2.2.6 on 2020-01-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockits',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='stockits',
            name='last_name',
        ),
    ]
