# Generated by Django 2.2.6 on 2020-01-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_auto_20200116_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockits',
            name='name',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
