# Generated by Django 2.2.6 on 2020-01-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_auto_20200116_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockits',
            name='grant_input',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='stockits',
            name='grant_output',
            field=models.BooleanField(null=True),
        ),
    ]
