# Generated by Django 2.2.6 on 2020-01-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_auto_20200120_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='stockists',
        ),
        migrations.AddField(
            model_name='stockits',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.Warehouse'),
        ),
    ]
